---
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
   script:
     - (mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam < ./script.sql)
   when: always
