---
- name: Ñreate user1
  hosts: test2
  become: true
  gather_facts: false

  tasks:
    - name: create user
      user:
        name: user1
        password: #hash
        shell: /bin/bash
        append: yes

    - name: create key
      user:
        name: user1
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
